# SwiftLint configuration
included:
  - Sources
  - Tests
excluded:
  - .build
  - .github
  - scripts
  - tools
  - integration
  - examples
  - docs

# Opt-in rules worth enabling
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - nimble_operator
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_imports
  - yoda_condition

# Reasonable defaults
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

identifier_name:
  min_length: 2
  max_length: 60
  excluded: [id, x, y, z]

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1200

function_parameter_count:
  warning: 7
  error: 10

cyclomatic_complexity:
  warning: 12
  error: 20

reporter: xcode
